### PR TITLE
Redone the file structure of the App.

### PR DESCRIPTION
**Pull request by XanderSchoeman**
### **Overview:**

- File structure changed to make more sense and to make navigation easier when looking at code.
- File Structure now also will be used when refactoring to MVVM(MVP in our case).
**NB!**
- All code will be refactored in the next part, this is just to prepare the file structure for the refactoring, so changes will be made in the next parts.

### CODE REVIEW

**Comment by XanderSchoeman** [comment]
Without putting in a file, it does now allow me to commit the actual folders for my App. So I just put in placeholder files.

**Comment by XanderSchoeman** [comment]
If there is perhaps another suggestion as to how I can commit folders in the future that would be much appreciated = ). Because it feels stupid to make placeholder files for each folder.

**Comment by Zamo22** [comment]
Why not rather move the files as needed there instead ? Not really too necessary to create all the folders now and only move/create files later, would rather create them only when needed. Unless I'm unaware of some requirement ?

**Comment by Prate-k** [comment]
I think the convention or from what i've used and seen before is having a blank file named ".gitkeep" rather than creating an actual swift file.

**Comment by XanderSchoeman** [comment]
Alright, do you suggest I do not merge this PR then with the folders?

**Comment by Zamo22** [comment]
I think Prateek's suggestion will solve your issue if you do want to go ahead creating the folders, but I would definitely suggest not to merge as is

**Comment by Tiewhan** [comment]
I personally agree with Zaheer on this. Don't like empty files doing nothing. However, if it this allows you to structure everything out and understand the plan ahead, who am I to fight that. I would go with Prateek's suggestion in that case.

**Comment by XanderSchoeman** [comment]
ok cool, I am going to close this PR then and perhaps make the files as they are needed. I looked into the .gitkeep, I found there is no documentation for it as it is a workaround for tracking empty directories in git. Although I think it might be best to just make the directories as needed after your suggestions as it is more ideal.

**Pull request closed without merging**
